# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
env:
  API_DIR: src/LocationGuesser.Api/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: false

      - name: Restore
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-restore

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/out
        working-directory: ${{env.API_DIR}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'ref/heads/main' }}

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'locationguesserdev'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: .
